### ISSUE TITLE
Tutorial Suggestions

### ISSUE THREAD

**Issue by Connor-A** [WittleWolfie/WW-Blueprint-Core#38]
Just logging some ideas for additional tutorials + documentation to help new users.

- General use tutorials that cover common tasks
          Adding/removing components from blueprints
          Altering component arguments
          Using LINQ with blueprint core
          Logging examples
    
- Several examples of OnConfig, and the different ways it can be used.
          OnConfig feels like one of the most powerful tools that blueprint core has available. A few examples of just how versatile it is would go a long way towards showing new users how to approach blueprint edits.

- Examples of how to create new event listeners in the context of blueprint core

The idea is that as a new user, I want to have a rough idea of how blueprint core wants me to solve problems before I attempt them myself.

**Comment by WittleWolfie** [comment]
Sorry I didn't respond earlier. I completely agree! Putting this on the 2.1 milestone so hopefully I can get some of this done by the end of June.

**Comment by WittleWolfie** [comment]
For the most part, general use tutorials are done. With 2.1 in particular I've restructured it into multiple pages for easier reading.

That includes examples of OnConfig, but to be honest, OnConfig is something that should be used sparingly. It exists as a catch-all for anything you can't do smoothly with the library, but ideally you don't need to use it. The majority of blueprint modifications should be handled using the explicit API methods such as component constructors and field set/modify or even edit component.

Regarding event listeners, I'll likely get to it in tutorials as I make more advanced tutorials but as of now there's no specific interaction between BPCore and the event system.

I'm going to close this out since I don't have any other improvements planned for 2.1, but I'll continue to expand the tutorial scope moving forward.

Going to close this one out
